# Generated by Django 5.2.3 on 2025-07-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlistings_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='auction_active',
            field=models.BooleanField(default=True),
        ),
    ]
